Rebuild node-sass in 'yarn install' to address the issue:
```
#!/bin/bash -eo pipefail
yarn build
yarn run v1.3.2
$ yarn linkage && ng-packagr -p package.json
$ mkdir -p dist && cd dist && cp ../package.json package.json && yarn link && cd ../testing && yarn link @howtimeflies/ngx-highcharts
success Registered "@howtimeflies/ngx-highcharts".
info You can now run `yarn link "@howtimeflies/ngx-highcharts"` in the projects where you want to use this module and it will be used instead.
warning package.json: No license field
success Using linked module for "@howtimeflies/ngx-highcharts".
/home/circleci/repo/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /home/circleci/repo/node_modules/node-sass/vendor/linux-x64-59/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 9.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 7.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/home/circleci/repo/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/circleci/repo/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/circleci/repo/node_modules/ng-packagr/lib/ng-v5/entry-point/resources/stylesheet.transform.js:22:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

https://circleci.com/gh/howtimeflies-io/ngx-highcharts/18